CREATE TABLE X3DDEC_ADMIN.DEC_CWP_CHANGE_REGISTER
(
	ID NUMBER GENERATED AS IDENTITY,
    SITE_CD    VARCHAR2(7) NOT NULL,
    CWP_NO    VARCHAR2(100) NOT NULL,
    CHANGE_DATE    DATE,
    INPUT_TYPE    VARCHAR2(10),
    CHANGE_ACTION    VARCHAR2(10),
    CHANGE_ATTRIBUTE    VARCHAR2(100),       
    BEFORE_VALUE    VARCHAR2(4000),
    AFTER_VALUE    VARCHAR2(4000),
    CHANGE_USER    VARCHAR2(100),
    CWP_OID    VARCHAR2(100), 
    PRIMARY KEY ( ID )
)TABLESPACE X3DDEC_TS;
