CREATE TABLE X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY (
  SITE_CD VARCHAR2(7),
  REQUEST_DATE VARCHAR2(8),
  INPUT_DATE VARCHAR2(8),
  ADDEDITDELETE VARCHAR2(20),
  ORIGINATOR VARCHAR2(20),
  CHANGE_ORIGINATOR VARCHAR2(20),
  CHANGE_DESC VARCHAR2(400),
  OLD_NO VARCHAR2(400),
  NEW_NO VARCHAR2(400),
  OPERATIONCENTER VARCHAR2(400),
  STATUS VARCHAR2(400),
  SUMMARY_OF_OUTCOME VARCHAR2(400),  
)TABLESPACE X3DDEC_TS;

COMMENT ON TABLE X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY IS '프로젝트 변경 이력';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.SITE_CD IS '프로젝트 코드';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.REQUEST_DATE IS 'Change History 요청 날짜';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.INPUT_DATE IS '작성 날짜';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.ADDEDITDELETE IS 'Add, Edit or Delete?';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.ORIGINATOR IS '작성자';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.CHANGE_ORIGINATOR IS '변경 요청자';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.CHANGE_DESC IS '변경 설명';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.OLD_NO IS 'Old No.';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.NEW_NO IS 'New No.';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.OPERATIONCENTER IS 'Operation Center';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.STATUS IS 'Status(Step 1 / Step 2 / Step 3)';
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.SUMMARY_OF_OUTCOME IS 'Summary of Outcome';

CREATE SEQUENCE X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

ALTER TABLE X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY ADD CHANGELOGNUMBER NUMBER;
ALTER TABLE X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY ADD ACCEPT_DATE DATE;
COMMENT ON COLUMN  X3DDEC_ADMIN.DEC_PROJECT_CHANGE_LOG_HISTORY.ACCEPT_DATE IS 'Change History 승인 날짜';
/*PROCESS_YN VARCHAR2(1),*/
