-- X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN definition

CREATE TABLE "X3DDEC_ADMIN"."IF_PROJECT_BIZ_LIST_IN" 
   (	"SITE_CD" VARCHAR2(7) NOT NULL ENABLE, 
	"CHG_SQNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"BIZCO_KNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CT_QUOTA_RT" NUMBER(18,3), 
	"REP_COMP_YN" VARCHAR2(1), 
	"IF_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "IF_PROJECT_BIZ_LIST_IN_PK" PRIMARY KEY ("SITE_CD", "CHG_SQNUM", "BIZCO_KNM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "X3DDEC_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "X3DDEC_TS" ;

COMMENT ON TABLE X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN IS '프로젝트 참여사정보';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN.SITE_CD IS '프로젝트 코드';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN.CHG_SQNUM IS '변경차수';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN.BIZCO_KNM IS '참여사명';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN.CT_QUOTA_RT IS '계약지분율(%)';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN.REP_COMP_YN IS '대표사구분';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_PROJECT_BIZ_LIST_IN.IF_DATE IS 'I/F 일시';

