CREATE TABLE X3DDEC_ADMIN.IF_LOG(
IF_SEQ NUMBER GENERATED AS IDENTITY,
IF_METHOD VARCHAR2(100),
IF_MSG CLOB,
IF_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE X3DDEC_ADMIN.IF_LOG
ADD CONSTRAINT IF_LOG_PK PRIMARY KEY (IF_SEQ,IF_METHOD)
ENABLE;

COMMENT ON TABLE X3DDEC_ADMIN.IF_LOG IS 'IF LOG';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_LOG.IF_SEQ IS 'IF Sequence';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_LOG.IF_METHOD IS 'IF Method명';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_LOG.IF_MSG IS 'IF log 메시지';
COMMENT ON COLUMN X3DDEC_ADMIN.IF_LOG.IF_DATE IS 'IF 일자';
