CREATE TABLE X3DDEC_ADMIN.DEC_DAILY_LOGIN_STATUS 
(
  LOGIN_DATE DATE NOT NULL,
  PERSON_NAME VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_DEC_DAILY_LOGIN_STATUS PRIMARY KEY(LOGIN_DATE,PERSON_NAME)
);
COMMENT ON TABLE X3DDEC_ADMIN.DEC_DAILY_LOGIN_STATUS IS 'Daily Login Status';
