CREATE TABLE X3DDEC_ADMIN.DEC_CONSTRUCTION_KPI
(
	ID NUMBER GENERATED AS IDENTITY,
    SITE_CD    VARCHAR2(7) NOT NULL,
    UNIT_ID    VARCHAR2(100) NOT NULL,
    DISCIPLINE    VARCHAR2(100) NOT NULL,
    CONSTRUCTION_ITEM    VARCHAR2(100) NOT NULL,
    TARGET    NUMBER,
    ACTUAL    NUMBER,
    TOTAL    NUMBER,
    KPIDATE    DATE DEFAULT SYSDATE,
    KPIWEEK  VARCHAR2(5),
    CUTOFFDATE    DATE DEFAULT SYSDATE,
    INPUTDATE    DATE DEFAULT SYSDATE,
    PRIMARY KEY ( ID )
)TABLESPACE X3DDEC_TS;

ALTER TABLE X3DDEC_ADMIN.DEC_CONSTRUCTION_KPI ADD UNIQUE (SITE_CD, UNIT_ID, CONSTRUCTION_ITEM, KPIDATE);
