CREATE TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA (
	SITE_CD VARCHAR2(7),
	UNIT_CD VARCHAR2(100),
	KEY_CD NUMBER(30,10),
	CUT_OFF_YEAR NUMBER(4),
	CUT_OFF_MONTH NUMBER(2),
	PRJ_BID_QTY NUMBER(30,10),
	PRJ_APPROVED_VO_QTY NUMBER(30,10),
	PRJ_REVISED_CONT_QTY NUMBER(30,10),
	PRJ_APPROVED_VO_QTY_BEFORE_BUDGET NUMBER(30,10),
	PRJ_VERIFIED_OVERBUDGET_QTY_BEFORE_BUDGET NUMBER(30,10),
	PRJ_BUDGET_QTY NUMBER(30,10),
	PRJ_APPROVED_VO_QTY_AFTER_BUDGET NUMBER(30,10),
	PRJ_VERIFIED_OVERBUDGET_QTY_AFTER_BUDGET NUMBER(30,10),
	PRJ_REVISED_BUDGET_QTY NUMBER(30,10),
	ENG_NET_PRESENT_QTY NUMBER(30,10),
	ENG_TO_GO_QTY NUMBER(30,10),
	ENG_TOTAL_FORECAST_QTY NUMBER(30,10),
	ENG_PREV_TOTAL_FORECAST_QTY NUMBER(30,10),
	ENG_PERIOD_DELTA NUMBER(30,10),
	VARIANCE NUMBER(30,10),
	TYPE1_REMARK VARCHAR2(3000),
	TYPE2_REMARK VARCHAR2(3000),
	CHANGE_DATE DATE,
	CHANGE_USER VARCHAR2(10),
	CONSTRAINT DEC_KEY_QUANTITY_MONTLY_DATA_PK PRIMARY KEY (SITE_CD,UNIT_CD,KEY_CD,CUT_OFF_YEAR,CUT_OFF_MONTH)
);
COMMENT ON TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA IS 'Key Quantity Tracking List 정보';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.SITE_CD IS '프로젝트 코드';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.UNIT_CD IS 'UNIT Code';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.KEY_CD IS 'Key Code';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.CUT_OFF_YEAR IS 'Target Year';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.CUT_OFF_MONTH IS 'Target Month';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_BID_QTY IS '입찰';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_APPROVED_VO_QTY IS '도급변경';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_REVISED_CONT_QTY IS '현재도급';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_APPROVED_VO_QTY_BEFORE_BUDGET IS '본실행 전 도급변경';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_VERIFIED_OVERBUDGET_QTY_BEFORE_BUDGET IS '본실행 전 도급미반영';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_BUDGET_QTY IS '본실행';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_APPROVED_VO_QTY_AFTER_BUDGET IS '본실행 후 도급변경';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_VERIFIED_OVERBUDGET_QTY_AFTER_BUDGET IS '본실행 후 실행미반영';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.PRJ_REVISED_BUDGET_QTY IS '승인예산물량';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.ENG_NET_PRESENT_QTY IS '출도확인물량';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.ENG_TO_GO_QTY IS '미출도확인물량';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.ENG_TOTAL_FORECAST_QTY IS '총물량';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.ENG_PREV_TOTAL_FORECAST_QTY IS '전월총물량';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.ENG_PERIOD_DELTA IS '월간 증감';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.VARIANCE IS '총물량 - 승인예산물량';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.TYPE1_REMARK IS 'Type1 Remark';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.TYPE2_REMARK IS 'Type2 Remark';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.CHANGE_DATE IS '변경일';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA.CHANGE_USER IS '변경자';

ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA MODIFY CHANGE_DATE DATE DEFAULT SYSDATE;

ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA MODIFY CHANGE_USER VARCHAR2(100);

ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA MODIFY KEY_CD VARCHAR2(10);

ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA ADD CUT_OFF_DATE DATE;

ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA ADD UNIT_ID VARCHAR2(50);

ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA DROP CONSTRAINT DEC_KEY_QUANTITY_MONTLY_DATA_PK;
ALTER TABLE X3DDEC_ADMIN.DEC_KEY_QUANTITY_MONTLY_DATA
ADD CONSTRAINT DEC_KEY_QUANTITY_MONTLY_DATA_PK PRIMARY KEY (SITE_CD,KEY_CD,CUT_OFF_YEAR,CUT_OFF_MONTH,UNIT_ID)
ENABLE;

