CREATE TABLE X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST (
	SITE_CD VARCHAR2(5) NOT NULL,
	CWP_NO VARCHAR2(30) NOT NULL,
	LINE_NO VARCHAR2(100) NOT NULL,
	ISO_NO VARCHAR2(100) NOT NULL,
	IDENT_CD VARCHAR2(20) NOT NULL,
	IWP_NO VARCHAR2(100) NOT NULL,
	IWP_OID VARCHAR2(100) NOT NULL,
	CONSTRAINT DEC_IWP_MATERIAL_LIST_PK PRIMARY KEY (SITE_CD, CWP_NO, LINE_NO, ISO_NO, IDENT_CD)
);

COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.SITE_CD IS '현장코드';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.CWP_NO IS 'CWP 번호';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.LINE_NO IS '지역명';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.ISO_NO IS 'LINE번호';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.IDENT_CD IS 'IDENT코드';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.IWP_NO IS 'IWP번호';
COMMENT ON COLUMN X3DDEC_ADMIN.DEC_IWP_MATERIAL_LIST.IWP_OID IS 'IWP ObjectId';